[programs.localnet]
furious_flowers = "DaoHYE9jbauRg4Kp6jtWmmK4soTq3qtdBMn5aYLSLZiM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/susanne/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
